#!/usr/bin/with-contenv bash

# make redis folders
mkdir -p \
	/config/{log/redis,redis} \
	/var/run/redis/

# copy redis defaults
[[ ! -f /config/redis/redis.conf ]] &&
	cp /defaults/redis.conf /config/redis/redis.conf

# permissions
chown -R abc:abc \
	/config/{log/redis,redis} \
	/var/run/redis/
