#!/usr/bin/with-contenv bash

# Set default PostgreSQL version
PGVERSION=${PG_VERSION:-14}

if ! command -v psql; then
	echo "**** Adding PostgreSQL to package install list ****"
	if [ -f /usr/bin/apt ]; then
		## Ubuntu
		if apt-cache show "postgresql-${PGVERSION}" >/dev/null 2>&1; then
			echo "postgresql-${PGVERSION}" >>/mod-repo-packages-to-install.list
		else
			echo "Version ${PGVERSION} of PostgreSQL is not available."
			sleep infinity
		fi
	fi

	if [ -f /sbin/apk ]; then
		# Alpine
		if apk info -vv | grep -q "postgresql${PGVERSION}"; then
			echo "postgresql${PGVERSION} \
postgresql${PGVERSION}-contrib" >>/mod-repo-packages-to-install.list
		else
			echo "Version ${PGVERSION} of PostgreSQL is not available."
			sleep infinity
		fi
	fi
else
	echo "**** PostgreSQL already installed, skipping ****"
fi
