#!/usr/bin/with-contenv bash

# Set default PostgreSQL version
PGVERSION=${PG_VERSION:-14}
ACTUALPGVERSION=${cat/config/postgres*/PG_VERSION}
PGDIR="${PGDIR}"

# Set PostgreSQL bin directory in the PATH
export PATH=$PATH:/usr/lib/postgresql/${PGVERSION}/bin/

# move old postgres folder to postgres<version>
if [ -d /config/postgres ]; then
	mv /config/postgres /config/postgres$(cat /config/postgres/PG_VERSION)
fi

# Upgrade postgres
if [ "${ACTUALPGVERSION}" -gt "${PGVERSION}" ]; then
	echo "Found an existing PostgreSQL installation with a different version."
	echo "Attempting to upgrade PostgreSQL to version ${PGVERSION}..."

	# Upgrade PostgreSQL version
	PREVIOUS_PGVERSION=$(cat /config/postgres/PG_VERSION)

	# Create new PostgreSQL directory
	NEW_PGDIR="/config/postgres${PGVERSION}"
	mkdir -p "$NEW_PGDIR"
	chown -R postgres:postgres "$NEW_PGDIR"

	# Upgrade PostgreSQL data directory
	pg_upgrade \
		--old-datadir="/config/postgres/$PREVIOUS_PGVERSION" \
		--new-datadir="$NEW_PGDIR" \
		--old-bindir="/usr/lib/postgresql/$PREVIOUS_PGVERSION/bin/" \
		--new-bindir="/usr/lib/postgresql/${PGVERSION}/bin"

	UPGRADE_SUCCESS=$?

	if [ $UPGRADE_SUCCESS -eq 0 ]; then
		echo "PostgreSQL successfully upgraded to version ${PGVERSION}"

		# Remove old PostgreSQL directory
		rm -rf "/config/postgres/$PREVIOUS_PGVERSION"
	else
		echo "Failed to upgrade PostgreSQL to version ${PGVERSION}"
		echo "Please check the logs for more details"
		sleep infinity
	fi
elif [ "${ACTUALPGVERSION}" = "${PGVERSION}" ]; then
	: # do nothing...
elif [ "${ACTUALPGVERSION}" -lt "${PGVERSION}" ]; then
	echo "You are attempting to downgrade PostgreSQL ${PGVERSION} to ${ACTUALPGVERSION}, this action is not supported."
	echo "Please modify the 'PG_VERSION' variable to ${ACTUALPGVERSION} or higher!"
fi

if [ ! -d /config/postgres* ]; then
	echo "Initializing PostgreSQL Database"
	mkdir -p ${PGDIR} /run/postgresql
	chown -R postgres:postgres ${PGDIR} /run/postgresql

	# Initialize PostgreSQL database
	s6-setuidgid postgres initdb -D ${PGDIR} --username=postgres
	s6-setuidgid postgres pg_ctl -D ${PGDIR} -o '-c listen_addresses= -p 5432' -w start
	s6-setuidgid postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
	s6-setuidgid postgres pg_ctl -D ${PGDIR} -m fast -w stop

	echo "PostgreSQL Database Initialised"
else
	echo "PostgreSQL Database Already Initialized"
fi
