#!/usr/bin/with-contenv bash

# Set default PostgreSQL version
PGVERSION=${PG_VERSION:-14}

# Set PostgreSQL bin directory in the PATH
export PATH=$PATH:/usr/lib/postgresql/$PGVERSION/bin/

# Function to upgrade PostgreSQL version
upgrade_postgres_version() {
	PREVIOUS_PGVERSION=$(cat /config/postgres/PG_VERSION)

	# Create new PostgreSQL directory
	NEW_PGDIR="/config/postgres$PGVERSION"
	mkdir -p "$NEW_PGDIR"
	chown -R postgres:postgres "$NEW_PGDIR"

	# Upgrade PostgreSQL data directory
	pg_upgrade \
		--old-datadir="/config/postgres/$PREVIOUS_PGVERSION" \
		--new-datadir="$NEW_PGDIR" \
		--old-bindir="/usr/lib/postgresql/$PREVIOUS_PGVERSION/bin/" \
		--new-bindir="/usr/lib/postgresql/$PGVERSION/bin"

	UPGRADE_SUCCESS=$?

	if [ $UPGRADE_SUCCESS -eq 0 ]; then
		echo "PostgreSQL successfully upgraded to version $PGVERSION"

		# Remove old PostgreSQL directory
		rm -rf "/config/postgres/$PREVIOUS_PGVERSION"
	else
		echo "Failed to upgrade PostgreSQL to version $PGVERSION"
		echo "Please check the logs for more details"
		exit 1
	fi
}

# Check if the PostgreSQL directory exists
if [ -d /config/postgres ]; then
	if [ -f /config/postgres/PG_VERSION ]; then
		# PostgreSQL directory exists and version is different
		if [ "$(cat /config/postgres/PG_VERSION)" != "$PGVERSION" ]; then
			echo "Found an existing PostgreSQL installation with a different version."
			echo "Attempting to upgrade PostgreSQL to version $PGVERSION..."

			# Upgrade PostgreSQL version
			upgrade_postgres_version
		else
			echo "PostgreSQL Database Already Initialized"
		fi
	else
		echo "Invalid PostgreSQL installation detected. Exiting..."
		exit 1
	fi
else
	echo "Initializing PostgreSQL Database"
	mkdir -p /config/postgres /run/postgresql
	chown -R postgres:postgres /config/postgres /run/postgresql

	# Initialize PostgreSQL database
	s6-setuidgid postgres initdb -D /config/postgres/ --username=postgres
	s6-setuidgid postgres pg_ctl -D /config/postgres/ -o '-c listen_addresses= -p 5432' -w start
	s6-setuidgid postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
	s6-setuidgid postgres pg_ctl -D /config/postgres/ -m fast -w stop

	echo "PostgreSQL Database Initialized"
fi
