#!/usr/bin/with-contenv bash

exec s6-setuidgid abc \
	redis-server /config/redis/redis.conf \
	--bind 127.0.0.1 \
	--port 6379 \
	--pidfile /var/run/redis/redis.pid \
	--always-show-logo no \
	--dir /config/redis \
	--logfile /config/log/redis/redis.log
