#!/usr/bin/with-contenv bash

# List of nextcloud dependencies
packages="ffmpeg gnu-libiconv imagemagick libxml2 php81-apcu php81-bcmath php81-bz2 php81-ctype php81-curl php81-dom php81-exif php81-ftp php81-gd php81-gmp php81-iconv php81-imap php81-intl php81-ldap php81-opcache php81-pcntl php81-pdo_mysql php81-pdo_pgsql php81-pdo_sqlite php81-pecl-imagick php81-pecl-memcached php81-pgsql php81-phar php81-posix php81-redis php81-sodium php81-sqlite3 php81-sysvsem php81-xmlreader php81-zip samba-client"

# hide apk 'No such file or directory'
apk update -q

package_list=$(apk info 2>/dev/null)

for package in $packages; do
	if ! grep -q "$package" <<<"$package_list"; then
		echo $package >>/mod-repo-packages-to-install.list
	fi
done

# 'php81-pecl-smbclient' is in the testing repo
apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing \
    php81-pecl-mcrypt \
    php81-pecl-smbclient
