#!/usr/bin/with-contenv bash

if ! command -v redis-server; then
	echo "**** Adding redis-server to package install list ****"
	echo "redis-server" >>/mod-repo-packages-to-install.list
else
	echo "**** redis-server already installed, skipping ****"
fi
