#!/usr/bin/with-contenv bash

if ! command -v fail2ban; then
	echo "**** Adding Fail2ban to package install list ****"
	if [ -f /usr/bin/apt ]; then
		## Ubuntu
		echo "This mod will not currently work on ubuntu"
	fi

	if [ -f /sbin/apk ]; then
		# Alpine
		echo "fail2ban \
msmtp \
nftables \
whois" >>/mod-repo-packages-to-install.list
	fi
else
	echo "**** Fail2ban already installed, skipping ****"
fi
